### ISSUE TITLE
Solargraph v0.44.2 fails to install or bundle

### ISSUE THREAD

**Issue by rrojan** [castwide/solargraph#531]
Hello all!

Lately I've been unable to install solargraph v0.44.2 for my Rails project.

Ruby version: 3.0.2 (same problem with 3.1.0)
Rails version: 6.1.4.4

Exception:
```
project-name on  dev [?] via  v14.17.0 via 💎 v3.0.2 
🕙 09:58:56 ➜ gem install solargraph
Exception while verifying /home/user/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/cache/solargraph-0.44.2.gem
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
```
Same thing happens when I add Solargraph to my Gemfile and try to bundle it.

Installation works fine with v0.43.3.
```
🕙 10:06:27 ✖  gem install solargraph -v 0.43.3
Fetching solargraph-0.43.3.gem
Successfully installed solargraph-0.43.3
Parsing documentation for solargraph-0.43.3
Installing ri documentation for solargraph-0.43.3
Done installing documentation for solargraph after 1 seconds
1 gem installed
```

I use rbenv to manage Ruby versions.

**Comment by castwide** [comment]
Can you run `solargraph scan` from your project's root directory and let me know if you get an error message with a stack trace?

**Comment by rrojan** [comment]
The installation works with Ruby 3.0.2 and Solargraph 0.44.3 now. Previously I encountered this problem with 0.44.2 and 0.44.1 (as mentioned above) but those seem to be gone with the new version.

Cheers, and thanks a lot for the fix!
