### ISSUE TITLE
Solargraph failing after upgrade to 0.41.0

### ISSUE THREAD

**Issue by tdegrunt** [castwide/solargraph#443]
Whenever I move around in the code it says the following:

```
[Error - 8:48:55 AM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `name' for "uikit":String
  Code: -32603 
```

We have a bundled gem called 'uikit', but the current open file does not have that text.

I ran `solargraph clean`, `solargraph bundle` too.

This is what I see in VSCode developer console:
```
​ Error: [NoMethodError] undefined method `name' for "uikit":String
	at handleResponse (/Users/tdegrunt/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477)
	at processMessageQueue (/Users/tdegrunt/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292)
	at Immediate.<anonymous> (/Users/tdegrunt/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276)
	at processImmediate (internal/timers.js:461)
```

I'm afraid that this isn't telling anyone anything though. 

I've tried checking out a new version of the code, so that possible lingering files are removed, but I'm not sure how to debug this further. I've enabled debug logging, but not sure where this can be seen.

**Comment by castwide** [comment]
This issue affects workspaces that automatically require bundled gems, e.g., via `require 'bundler/require` or `Bundler.require`. Rails apps do this, so there's plenty of impact. I'm working on an improvement to how those cases get handled. In the meantime, gem v0.41.1 reverts to the same process that worked in 0.40.x.

**Comment by tdegrunt** [comment]
Sounds good, too bad you had to revert stuff. :( - Thanks!
